### PR TITLE
Timeout fix

### PR DESCRIPTION
**Pull request by devops-rob**
Adds timeout configuration for resource and data source

### CODE REVIEW

**Comment by lucymhdavies** [comment]
Seeing if I can replicate the issues with the tests locally.
https://github.com/devops-rob/terraform-provider-terracurl/actions/runs/4522551648/jobs/7965104589

Like you've seen yourself, It Works On My Machine.


But... that's with TF v1.4.2

```
✔ strawb@HashiBook ~/git_src/github.com/devops-rob/terraform-provider-terracurl [timeout-fix|✔]
$ go test -v -cover ./internal/provider/
=== RUN   TestAccdataSourceCurlRequest
--- PASS: TestAccdataSourceCurlRequest (3.49s)
=== RUN   TestAccdataSourceRetriesOnFailure
--- PASS: TestAccdataSourceRetriesOnFailure (1.97s)
=== RUN   TestAccdataSourceCurlRequestTimeout
    data_source_curl_request_test.go:183: API call took 989.492506ms
--- PASS: TestAccdataSourceCurlRequestTimeout (0.99s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccresourceCurl
--- PASS: TestAccresourceCurl (1.50s)
=== RUN   TestAccresourceRetriesOnFailure
--- PASS: TestAccresourceRetriesOnFailure (2.59s)
=== RUN   TestAccresourceRetriesOnError
--- PASS: TestAccresourceRetriesOnError (2.60s)
=== RUN   TestAccresourceCurlBody
--- PASS: TestAccresourceCurlBody (1.59s)
=== RUN   TestAccresourceCurlParameters
--- PASS: TestAccresourceCurlParameters (1.64s)
=== RUN   TestAccresourceNoDestroy
--- PASS: TestAccresourceNoDestroy (1.61s)
PASS
	github.com/devops-rob/terraform-provider-terracurl/internal/provider	coverage: 72.5% of statements
ok  	github.com/devops-rob/terraform-provider-terracurl/internal/provider	19.639s	coverage: 72.5% of statements

✔ strawb@HashiBook ~/git_src/github.com/devops-rob/terraform-provider-terracurl [timeout-fix|✔]
$ go version
go version go1.20.2 darwin/amd64

✔ strawb@HashiBook ~/git_src/github.com/devops-rob/terraform-provider-terracurl [timeout-fix|✔]
$ terraform version
Terraform v1.4.2
on darwin_amd64
```



I notice that you're doing matrix tests for various different Terraform versions, and it's 0.13 which is failing.

I'll see if it fails for me on that version too.

**Comment by devops-rob** [comment]
Yea it's super odd. I'm really at a loss as to what the difference is between my local testing environment and the GHA environment

**Comment by lucymhdavies** [comment]
Created https://github.com/devops-rob/terraform-provider-terracurl/issues/74 to track the issue

**Comment by lucymhdavies** [comment]
Now https://github.com/devops-rob/terraform-provider-terracurl/issues/74 has been fixed... at some point, I'll spend some time to rebase this and resolve the conflicts :)

**Comment by devops-rob** [comment]
@lucymhdavies finally got round to fixing this. Merging now. All tests are passing

**Pull request merged**
